### ISSUE TITLE
[BUG] (Non-breaking) Incorrect information regarding data types on lab02

### ISSUE THREAD

**Issue by SDSTony** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#169] opened 2023-03-13 14:49 UTC
#### **Priority**
Non-breaking

#### **Lab/Demo Number/Name**
02-load-data-with-power-query-in-power-bi-desktop

#### **Describe the bug**
On task 7 - step 10, it says `The fixed decimal number data type stores values with full precision, and so requires more storage space that decimal number.` 

However, `fixed decimal numbers` does not always require more storage space than decimal numbers. In fact, if we use the columns from the lab as an example, `Cost`, `Sales`, and `Unit Price` columns require less storage space to store if it is in `fixed decimal number` type compared to the `decimal number`. 

- storage space for `decimal number` (data type: double): 
![image](https://user-images.githubusercontent.com/46511987/224734101-0ae6400b-27d1-403b-8082-47e8034e8217.png)

- storage space for `fixed decimal number` (data type: decimal): 
![image](https://user-images.githubusercontent.com/46511987/224734128-2735fcdb-6b43-4aaf-9216-ab8de68ce3ee.png)

Above images are from the result of the VertiPaq Analyzer in DAX Studio. We can see that same columns in `fixed decimal number` (data type in `decimal`) requires less storage space compared to `decimal number` (data type in `double`) due to less precision. (`Fixed decimal number` only stores up to 4 digits to the right of decimal point.)

#### **Screenshots**
![image](https://user-images.githubusercontent.com/46511987/224726332-7a615c03-bb30-4f90-85ae-82ffffc7469d.png)

#### **To Reproduce**
N/A

#### **Expected behavior/Suggested Change**
Either delete the sentence, or edit it along the lines of `The fixed decimal number data type stores fixed 4 digits to the right of the decimal point, so it generally requires less storage space than decimal number, which can have decimal separator anywhere in the number.`

#### **Additional context**
Reference: 
1. https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-types#decimal-number
2. https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-types#fixed-decimal-number
3. https://learn.microsoft.com/en-us/analysis-services/tabular-models/data-types-supported-ssas-tabular?redirectedfrom=MSDN&view=asallproducts-allversions#bkmk_data_types

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by arnoldvilleneuve** [comment] 2023-03-13 14:53
Nicely pointed out Tony. 
Arnold Villeneuve 613-833-0984 

    On Monday, March 13, 2023 at 10:49:47 a.m. EDT, Tony (Sungjin) Ahn ***@***.***> wrote:  
 
 


Priority

Non-breaking

Lab/Demo Number/Name

02-load-data-with-power-query-in-power-bi-desktop

Describe the bug

On task 7 - step 10, it says The fixed decimal number data type stores values with full precision, and so requires more storage space that decimal number.

However, fixed decimal numbers does not always require more storage space than decimal numbers. In fact, if we use the columns from the lab as an example, Cost, Sales, and Unit Price columns require less storage space to store if it is in fixed decimal number type compared to the decimal number.
   
   -    
storage space for decimal number (data type: double):   


   -    
storage space for fixed decimal number (data type: decimal):   



Above images are from the result of the VertiPaq Analyzer in DAX Studio. We can see that same columns in fixed decimal number (data type in decimal) requires less storage space compared to decimal number (data type in double) due to less precision. (Fixed decimal number only stores up to 4 digits to the right of decimal point.)

Screenshots



To Reproduce

N/A

Expected behavior/Suggested Change

Either delete the sentence, or edit it along the lines of The fixed decimal number data type stores fixed 4 digits to the right of the decimal point, so it generally requires less storage space than decimal number, which can have decimal separator anywhere in the number.

Additional context

Reference: https://learn.microsoft.com/en-us/power-bi/connect-data/desktop-data-types#decimal-number

Note: To share feedback for the slides, please use the MCT Courseware Forum.

**Comment by AngieRudduck** [comment] 2023-03-22 00:37
@SDSTony Thanks Tony for this note, I appreciate the level of detail you provided to support the issue!

I agree that the verbiage should be updated if the experience you shared is always the case. I also think that most candidates for the PL-300 course and certification are not yet at the level you are sharing here. While they may know to use one data type over the other, DAX Studio is out of scope for the curriculum. 

I'll validate the data types and review the verbiage to reflect in a coming update. Thanks again!

**Comment by SDSTony** [comment] 2023-04-25 12:21
@AngieRudduck Hello Angie, thanks for reviewing this issue. 

I agree that DAX Studio should be out of the scope for the curriculum, and I'm not trying to suggest that we should add it into the PL-300 courseware. 

The reason I brought up the screenshots of DAX Studio is to share the references which show that `fixed decimal` data types need less storage space than compared to `decimal` data types. 

`Fixed decimal` data types will only keep up to 4 digits after the decimal point and will truncate anything that comes after. So it will indeed need less storage space than `decimal` data type which can store all the decimal points up to 15 digits max after the decimal point. 

The reason I'm creating this issue is because in module 6, when we talk about optimizing model performance, one of the methods for optimization is to use the appropriate data types. Because the storage space concept for data types is currently incorrectly addressed in the instructions of this this lab, learners can get confused in module 6, thinking `fixed decimal` will use more space than `decimal` data type. 

Thanks and let me know if you need additional info!

**Comment by AngieRudduck** [comment] 2023-05-10 19:00
Sorry for the delay. After review, the storage reference is misleading in this section. I've updated it to be more about the precision of fixed decimal.

*The fixed decimal number data type allows for 19 digits, and allows for more precision to avoid rounding errors. It’s important to use the fixed decimal number type for financial values, or rates (like exchange rates).*

**Closed as completed by AngieRudduck** 2023-05-10 19:00 UTC
Labels: in review
