### ISSUE TITLE
Region with 10 or 11 rows (Corporate HQ has been removed from the lab?)

### ISSUE THREAD

**Issue by weslbo** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#111] opened 2022-11-28 14:32 UTC
# Module: 02
#### Step: 5 In the status bar, verify that the query has four columns and 10 rows.

Description of issue

The Region query has 11 rows instead of 10. Please validate or update instructions and screenshot. 
![image](https://user-images.githubusercontent.com/53346841/204302759-ad19ecee-fa0f-4cbe-aac7-0bf0bce476b3.png)

Or, alternatively, add the Filter again (to remove Corporate HQ). This is a screenshot of the solution file for this lab:

![image](https://user-images.githubusercontent.com/53346841/204303452-d3b4cd58-6ba2-48ef-919d-d35f23906fe6.png)

Repro steps:

1.
1.
1.

**Comment by christabelle** [comment] 2022-11-28 18:35
@weslbo I was going to post this today as well! Thanks Wesley!

**Comment by AngieRudduck** [comment] 2022-11-30 21:37
@weslbo  good catch. I see the mistake now was due to a previous issue opened that said the primary key was no longer including a 0, and upon further investigation based on your issue, I see that the issue is that it's the ALTERNATE key with 0 value. I'll revert to old instructions in next update.

**Comment by VitalyMCT** [comment] 2022-12-05 02:35
@AngieRudduck Can you please advise how soon the fix will be published?

**Comment by AngieRudduck** [comment] 2022-12-15 03:09
We will apply bug fixes by end of next week.

**Comment by AngieRudduck** [comment] 2022-12-15 03:49
This is a duplicate of issue #109 so I'm closing this, but fix will still go.

**Closed as completed by AngieRudduck** 2022-12-15 03:49 UTC
