### ISSUE TITLE
08-perform-data-analysis-in-power-bi-desktop.md Exercise 1 lab step changes

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/PL-300-Microsoft-Power-BI-Data-Analyst#155] opened 2023-01-21 02:07 UTC
#### **Priority**
Critical

#### **Lab/Demo Number/Name**
08-perform-data-analysis-in-power-bi-desktop.md
Exercise 1, Task 2, Step 2 and 3
and
Exercise 1 Task 3, Step 4 and 5

#### **Describe the bug**
Exercise 1, Task 2, Step 2 and 3

Step 2 states: "Select New > Dataset. This opens the Get Data page, and under Create new content > Files, select Get."

The interface has changed I believe. It should say: " Click upload, then Browse. 

Step 3 should now state: "Navigate to D:\PL300\Labs\08-perform-data-analysis-in-power-bi-desktop\Starter folder."

Exercise 1 Task 3, Step 4 and 5

Step 4 states: "Next, we repeat the steps to Get Data from lab 1. From the Home ribbon tab > Data group, select Power BI Datasets."

Firstly, I don't know what the phrase "we repeat the steps to Get Data from lab 1" means and should be deleted. 

Also, it seems the interface has changed. Step 4 just needs to state now: "On the Home tab, in the Data group, click Get Data, then Power BI datasets."

Step 5 should state: "On the Data hub dialog box, Select the Sales Analysis dataset, then click Connect." 

#### **Screenshots**
Task 2 step 2:

![Lab 8-1 Step 2](https://user-images.githubusercontent.com/16696370/213837766-c38a3fde-45c4-41db-9c7c-7a8c8919a220.jpg)

Task 2 step 3:

![Lab 8-1 Step 3](https://user-images.githubusercontent.com/16696370/213837943-e7a56b17-1d0d-4ed1-b4e9-05c41d71e76f.jpg)

Task 3 Step 4:

![Lab 8-2 Step 4](https://user-images.githubusercontent.com/16696370/213838041-0c633700-a59f-4982-adca-d697ced7a2e9.jpg)

Task 3 Step 5: 

![Lab 8-2 Step 5](https://user-images.githubusercontent.com/16696370/213838107-08ee952c-a374-4448-86ca-afe5ff4a2e06.jpg)

#### **Expected behavior/Suggested Change**
Update needed listed above

#### **Additional context**

***Note**: To share feedback for the slides, please use the [MCT Courseware Forum](https://www.microsoft.com/learning/mct-courseware-forum.aspx).*

**Comment by VitalyMCT** [comment] 2023-01-31 14:57
@AngieRudduck Can this item and the 2 related open issues (#159 and #160) for the same UI change please be merged into the current instructions on a priority basis? It's a simple fix. The issue is impacting students in live classrooms.

**Comment by arnoldvilleneuve** [comment] 2023-01-31 19:17
Agreed. 
Arnold Villeneuve 613-833-0984 

    On Tuesday, January 31, 2023 at 09:57:46 a.m. EST, Vitaly Livshits ***@***.***> wrote:  
 
 


@AngieRudduck Can this item and the 2 related open issues for the same UI change please be merged into the current instructions on a priority basis? It's a simple fix. The issue is impacting students in live classrooms.

**Comment by AngieRudduck** [comment] 2023-02-01 19:47
@arnoldvilleneuve @VitalyMCT @JeffSmalley, I will roll this out ASAP. Please note that the changes that come to Power BI service can be as frequent as weekly, so updates will roll as soon as possible. In consideration, this was already updated in the last 30 days to reflect a different experience, so it's changed already.

**Closed as completed** 2023-02-03 20:31 UTC
